### ISSUE TITLE
Spruce error when trying to deploy

### ISSUE THREAD

**Issue by bodymindarts** [genesis-community/shield-genesis-kit#1]
```
- $.instance_groups.shield.networks.0.static_ips: `$.networks.1.subnets.0.static` could not be found in the datastructure
 - $.instance_groups.shield.properties.shield.daemon.domain: Unable to resolve `instance_groups.shield.networks.0.static_ips.0`: $.instance_groups.shield.networks.0.static_ips [=(( static_ips 0 ))] is a scalar (not a map or a list)
```
This is my cloud-config shield network:
```
networks:
- name: shield
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    reserved:
    - 10.0.1.0-10.0.1.31
    - 10.0.1.64-10.0.1.255
    azs: [z1, z2, z3]
    cloud_properties:
      network_name: misthos
      subnetwork_name: misthos-proto
      tags: [bosh-agent, proto-shield]
```

**Comment by bodymindarts** [comment]
Okay I added a static ip and then get this:
```
2 error(s) detected:
 - $.instance_groups.shield.networks.0.static_ips: could not find AZ z1 (in network AZS [z1 z2 z3])
 - $.instance_groups.shield.properties.shield.daemon.domain: Unable to resolve `instance_groups.shield.networks.0.static_ips.0`: $.instance_groups.shield.networks.0.static_ips [=(( static_ips 0 ))] is a scalar (not a map or a list)
```

**Comment by bodymindarts** [comment]
I've fixed it by adding:
```
instance_groups:
- name: shield
  networks:
  - name: (( grab params.shield_network ))
    static_ips: [ 10.0.1.32 ]
```
to my deployment file.
Why is the static ip even required?
