### ISSUE TITLE
Lessen check script requirements for certificates

### ISSUE THREAD

**Issue by thomasmitchell** [genesis-community/shield-genesis-kit#15]
I'm trying to deploy a custom certificate to SHIELD. This involves writing the ca certificate to the Vault, and also the server certificate and server key to the Vault. This is all the deployment actually requires, but Genesis checks for the ca combined, crl, and key, and also the combined on the server. This aren't needed by the deployment, so they shouldn't be checked at deploy time.

**Comment by thomasmitchell** [comment]
It also requires the CA serial, which is unneeded.

**Comment by jhunt** [comment]
Can you provide terminal output of a failing check?

**Comment by thomasmitchell** [comment]
```
tommitchell@smoermsbb01c:~/repos/shield-deployments$ genesis deploy smo-control-plane.yml
Checking availability of the 'smo-control-plane' BOSH director...ok
Preparing to deploy smo-control-plane to 'smo-control-plane' BOSH director.

- Fetching cloud config from 'smo-control-plane'
Downloading cloud config from 'smo-control-plane' BOSH director...ok
- Running preflight checks against [smo-control-plane]:

[smo-control-plane] running cloud-config and environmental parameters checks...
  [Checking cloud config]
  ✔  vm_type 'small' exists
  ✔  disk_type 'shield' exists
  ✔  network 'shield' exists
  cloud-config [OK]
  checking if our certificates match the SHIELD external domain (shield.s1.jhaerms.com)...
    - secret/smo/control/plane/shield/certs/server [OK]
  environment files [OK]

[smo-control-plane] running credentials and certificates checks...
  Retrieving secrets for smo/control/plane/shield...ok

  [Checking generated credentials]
  ✔  secret/smo/control/plane/shield/agent [ssh]

  [Checking generated certificates]
  ✘  secret/smo/control/plane/shield/certs/ca [CA certificate]
     ✘  :combined
     ✘  :crl
     ✘  :key
     ✘  :serial
  ✘  secret/smo/control/plane/shield/certs/server [certificate]
     ✘  :combined
  ✔  secret/smo/control/plane/shield/vault/ca [CA certificate]
  ✔  secret/smo/control/plane/shield/vault/server [certificate]

! Kit preflight checks failed; deployment operation halted.
```

**Comment by thomasmitchell** [comment]
Current workaround is writing all the necessary keys with "placeholder" as their values.

**Comment by jhunt** [comment]
This is a Genesis core behavior.  I believe it is verifying these _auxiliary_ fields since some of them are used for auto-generating certs signed _by_ the CA (which in your case doesn't matter).

We should probably migrate this issue, and https://github.com/genesis-community/vault-genesis-kit/issues/18 over to https://github.com/genesis-community/genesis.

**Comment by dennisjbell** [comment]
Use the following `kit-overrides.yml` file (and genesis v2.7.19 or higher) to surgically alter the kit behaviour:

```
---
certificates:
  base:
    certs: ((prune))

provided:
  base:
    certs/ca:
      keys:
        certificate: 
          prompt: "Please provide the Shield CA certificate"
          multiline: true
    certs/server:
      keys:
        certificate:
          prompt: "Please provide the Shield TLS certificate"
          multiline: true
        key:
          prompt: "Please provide the Shield TLS key"
          multiline: true
```
